### ISSUE TITLE
Display display of ingredients can be confusing

### ISSUE THREAD

**Issue by jayaddison** [openculinary/frontend#103]
**Describe the bug**
The application currently displays the metadata relating to each ingredient instead of the full original ingredient description.

For example, for [this recipe](https://www.reciperadar.com/#search&action=view&id=Bkve6Jq8G7b15jEKabPFJHECRv) we currently render the following data:

![image](https://user-images.githubusercontent.com/55152140/79216879-d2a39300-7e45-11ea-87a3-d070090660a0.png)

For some ingredients, we lose information compared to the original ingredient descriptions:

```
$ curl -s -XPOST -H 'Host: crawler' localhost:30080/crawl --data "url=https://www.bbcgoodfood.com/recipes/buttery-potato-cake" | jq '.ingredients[] | { product: .product.product, quantity: .quantity, units: .units, description: .description }'
{
  "product": "potatoes",
  "quantity": 250,
  "units": "g",
  "description": "1¼kg desirée potatoes"
}
{
  "product": "butter",
  "quantity": 50,
  "units": "g",
  "description": "50g butter"
}
```
We would like to keep the metadata we've added since it helps us indicate what ingredients have matched.

However we should also ensure that the user sees the full intended ingredient description from the author.

**To Reproduce**
1. Go to https://www.reciperadar.com/#search&action=view&id=Bkve6Jq8G7b15jEKabPFJHECRv
2. Inspect the ingredient details
3. Click through to the source document at https://www.bbcgoodfood.com/recipes/buttery-potato-cake
4. Observe the full ingredient descriptions that contain additional information

**Expected behavior**
The user should be able to view the full description in the application.

Relates to #94

**Comment by jayaddison** [comment]
Work will begin to resolve this issue soon.

RecipeRadar should not simply copy existing recipes -- it should serve as a genuine search engine that improves access to existing and enriched content from the public web while also providing attribution and hyperlinks to original sources.

Those sources should continue to be accessible directly from RecipeRadar when their content is displayed.  When descriptive recipe text (such as ingredients and instructions) is presented to the user, the overall experience is intended to provide additional metadata and value compared to the original source.

Given these considerations, the suggested approach is that metadata should be extracted from each ingredient ingredient and instruction line and that this additional content should be [interpolated](https://en.wikipedia.org/wiki/String_interpolation) with the original text.

For example, given the input:
`three small carrots, peeled and chopped`

We should produce an output such as:
`{quantity: 3, product: "carrots", description: "{quantity} small {product}, peeled and chopped"}`

This should eventually achieve the best of all worlds - full ingredient descriptive text will be visible to the user, RecipeRadar will be able to highlight matching ingredient names and display quantities in a manner that is [localizable and convertible](https://github.com/openculinary/frontend/issues/2), and the original author and publisher's sources will be credited and faithfully represented.

The implementation of this may not be perfect initially; ingredient parsing, for example, will need work.  Fortunately `ingreedy-py` provides a convenient place to [collect parsing test cases](https://github.com/openculinary/ingreedy-py/blob/3a44b1496741a3fa380fb61cf29e13d168f980fc/ingreedytest.py#L57-L63) and can be improved over time.

cc @queencitra

**Comment by queencitra** [comment]
Thank you to solve it @jayaddison
