### ISSUE TITLE
Potential API integrations !

### ISSUE THREAD

**Issue by SumeetMoray** [openculinary/frontend#85]
Whether to offer a commercial integration or a free integration that's upto you. But i believe that having few integrations is a very good to make this project available for others to use. 

You can provide a small library. Which anyone can include in their source code and start using your project. 

Dont try to implement too many features initally. And keep things simple. If you get good response and people like it then you can add more features !

**Comment by jayaddison** [comment]
Hi @SumeetMoray - could you be a little more specific about what kind of integrations you are suggesting here?  It would be good to describe the issue in a way that can be resolved by changes to the code.

If you'd like to consider integrations between your NearbyShops project and RecipeRadar, that would certainly be of interest - it'd be great for users to be able to see prices and availability for ingredients nearby.

**Comment by SumeetMoray** [comment]
Hi ... @jayaddison you can create a small library project with android studio. Anyone who wants to integrate RecipeRadar will use this integration. They can add it as a dependency. 
Its really easy and probably just require few hours or a week to develop !

Yes we will explore ... how to put this integration in the app.

**Comment by jayaddison** [comment]
@SumeetMoray That sounds great; the ability for Android apps to embed a small library and use RecipeRadar functionality could be very useful.

Let's pick one item of functionality to start with.  What might be the most useful feature from RecipeRadar for Android app developers to use?

**Comment by jayaddison** [comment]
Closing this issue for now; API integrations remain worth considering, and we can look into this again in future.  Please feel free to share any ideas about features that app integrations could use, and we can re-open this issue if and when discussion begins again.
