### ISSUE TITLE
Suggest ingredients based on partial name match

### ISSUE THREAD

**Issue by queencitra** [openculinary/frontend#90]
Can’t find use partial search. e.g. creamer for sweetened condensed non-dairy creamer. Right now the only I can do is prefix search.

**Comment by jayaddison** [comment]
Thanks for reporting this @queencitra - agreed that this would be useful functionality.

**Comment by jayaddison** [comment]
@queencitra This should now be implemented; I'm going to hold this issue open for a little longer because I'm still testing it, but if you could try out some sample searches when you have time, hopefully you'll find that you now get suggestions based on partial ingredient names.

**Comment by jayaddison** [comment]
Ok, I'm confident enough that this is working correctly for me to close the issue; please feel free to re-open this and/or raise any related issues.
