### ISSUE TITLE
Display same ingredient in different unit conversion on 'Recipes' Result

### ISSUE THREAD

**Issue by queencitra** [openculinary/frontend#92]
On some recipes, I found same ingredient in different quantity or unit conversion. e.g.  [Mango pudding](https://tastykitchen.com/recipes/desserts/mango-pudding/). On Ingredients feature, it says 1 mango and 2 mangoes. If I checked to the link, it says 1 package Mango Jelly and 2 whole Mangoes. It makes confused.

**To Reproduce**
1. Go to 'search menu'
2. Add 'mango'
3. Click 'Find recipes'
4. Scroll down
5. See on highlight based searching keyword

**Expected behavior**
Adding mango jelly and whole mango on db then displays result keyword on Ingredients feature based the referring recipes

**Screenshots**
<img width="1114" alt="Screen Shot 2020-04-11 at 08 09 29" src="https://user-images.githubusercontent.com/55746560/79031819-e47a0180-7bcb-11ea-84f0-54a7db032e44.png">

**Comment by jayaddison** [comment]
This should now be resolved thanks to #127 

![image](https://user-images.githubusercontent.com/55152140/80408945-ed531e80-88bf-11ea-82c0-6285256cdf8b.png)

Please verify when you have time - and file more issues for any other difficult or confusing recipes :)
